# Generated by Django 4.2.17 on 2024-12-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
