# Generated by Django 4.2.17 on 2024-12-22 21:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('deadlines', models.IntegerField()),
                ('income', models.FloatField()),
                ('company', models.CharField(max_length=255)),
                ('time_working', models.IntegerField(help_text='Time working in months')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('deadlines', models.IntegerField(help_text='Deadlines in months')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expire', models.DateTimeField(blank=True, help_text='Expiration date of the loan', null=True)),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('date_expire', models.DateTimeField(default=datetime.datetime(2024, 12, 29, 21, 21, 21, 175951, tzinfo=datetime.timezone.utc))),
                ('id_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.transfer')),
            ],
        ),
    ]
