# Generated by Django 4.2.17 on 2024-12-24 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_solicitude_loan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitude',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 14, 26, 42, 877349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='code',
            name='id_transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.transfer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
