# Generated by Django 4.2.17 on 2024-12-27 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_solicitude_state_alter_code_date_expire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 17, 40, 22, 578544, tzinfo=datetime.timezone.utc)),
        ),
    ]
