# Generated by Django 4.2.17 on 2024-12-28 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_user_cash_alter_code_date_expire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cash',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='code',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 14, 29, 49, 169511, tzinfo=datetime.timezone.utc)),
        ),
    ]
