# Generated by Django 4.2.17 on 2025-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_rename_cash_user_balance_alter_code_date_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitude',
            name='id_user',
        ),
        migrations.AddField(
            model_name='loan',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='time_working',
            field=models.IntegerField(blank=True, help_text='Time working in months', null=True),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Solicitude',
        ),
    ]
