# Generated by Django 4.2.17 on 2025-01-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
